apiVersion: v1
kind: Secret
metadata: 
    name: mysql-secret
type: Opaque
data: 
    mysql-admin-password: eWFzaW4xMjM=
    mysql-root-password: UjEyMzRy



# Kevser123 ve R1234r şifreleri önce encode edilmeli bunun için
#echo -n 'R1234r' | base64   --->  mysql-root-password olarak mysql-secret.yaml dosyasında adreslenir
#echo -n 'Kevser123' | base64 ----> mysql-admin-password olarak mysql-secret.yaml dosyasında adreslenir

# Kevser123 ve R1234r şifreleri decode etmek için
# echo -n 'UjEyMzRy' | base64 --decode     ---> It gives root us poassword
# echo -n 'eWFzaW4xMjM=' | base64 --decode   ---> It gives us admin password